name: IoT Demo

on: workflow_dispatch

env:
  AZURE_RG: ${{ secrets.AZURE_RG }}

jobs:

  depoying-iac-template:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Azure CLI script
        uses: azure/CLI@v1
        with:
          azcliversion: 2.30.0 # Optional
          inlineScript: |
            az group create --location eastus -n $AZURE_RG
            
  deploying-iot-hub:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [depoying-iac-template]
    steps:
      # Checkout code
    - uses: actions/checkout@main
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Deploy Bicep template
    - name: Run Bicep deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./IaC/poc2/main.bicep
        parameters: ./IaC/poc2/azuredeploy.parameters.json
            
  create-issue:
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs: [deploying-iot-hub]
    steps:
      - name: create-issue
        uses: oaviles/issue_action@v1
        with:
          issue-title: "Resource Group creation fail: ${{ github.sha }}"
          issue-body: "Validate orchestration workflow"
          repo-token: ${{secrets.GITHUB_TOKEN}}
